language: csharp
mono: none
dotnet: 2.1.4
dist: trusty
osx_image: xcode8.3
sudo: required

services:
  - docker

os:
  - linux
  - osx

script:
  - dotnet test wigc_test/wigc_test.csproj
  - dotnet run --project willitgocd/willitgocd.csproj -- help || true
  - dotnet run --project willitgocd/willitgocd.csproj -- xml -f wigc_test/data/with_environments.xml
  - dotnet run --project willitgocd/willitgocd.csproj -- xml -f wigc_test/data/without_environments.xml
